

import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:hwzn_herstation/general/blocks/auth_cubit/auth_cubit.dart';
import 'package:hwzn_herstation/general/blocks/user_cubit/user_cubit.dart';
import 'package:hwzn_herstation/general/constants/modals/LoadingDialog.dart';
import 'package:hwzn_herstation/general/helper/storage/Storage.dart';
import 'package:hwzn_herstation/general/models/LocationModel.dart';
import 'package:hwzn_herstation/general/models/home_model.dart';
import 'package:hwzn_herstation/general/models/update_address_data/update_address_data.dart';
import 'package:hwzn_herstation/general/models/user_model/user_model.dart';
import 'package:hwzn_herstation/general/resources/GeneralRepoImports.dart';
import 'package:hwzn_herstation/general/screens/location_address/location_cubit/location_cubit.dart';
import 'package:hwzn_herstation/general/utilities/routers/RouterImports.gr.dart';
import 'package:hwzn_herstation/makeup_artist/screens/makeup_artisit_home/tabs/makeup_artist_main/MakeupArtistMainImports.dart';
import 'package:hwzn_herstation/makeup_artist/screens/makeup_artisit_home/tabs/makeup_artist_main/widgets/MakeupArtistWidgetsImports.dart';
import 'package:hwzn_herstation/makeup_artist/screens/makeup_artisit_home/widgets/MakeupArtistHomeWidgetsImports.dart';
import 'package:hwzn_herstation/res.dart';
import 'package:hwzn_herstation/user/screens/main_home/tabs/my_appointment/MyAppointmentsImports.dart';
import 'package:hwzn_herstation/user/screens/main_home/tabs/user_profile/UserProfileImports.dart';
import '../../../general/helper/helper_methods/Map_Methods.dart';
import '../../../general/packages/generic_bloc/generic_cubit.dart';
part 'MakeupArtistHome.dart';
part 'MakeupArtistHomeData.dart';
